### PR TITLE
Update Typeable usage for GHC >= 7.7

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by ChrisKuklewicz** [comment]
Thanks! I will take a look over the XMas holiday

**Comment by bgamari** [comment]
Just a gentle reminder.

**Comment by JohnLato** [comment]
ghc-7.8 RC1 is out, perhaps you could look at this soon?

**Comment by qnikst** [comment]
Patches were applied and tested under ghc-7.8 RC1 in Gentoo. Works well.

**Pull request merged**
